apiVersion: v1
kind: Secret 

metadata: 
  name: mongodb-secret 
  namespace: flask-project 

type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: demo-user
  MONGO_INITDB_ROOT_PASSWORD: demo-password
  